name: gcc try fftw

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install fftw
        run: sudo apt install libfftw3-dev ninja-build neofetch && pip install numpy scipy && neofetch

      - name: configure
        run: cmake -S . -B ./build -G Ninja -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE

      - name: build
        run: cmake --build ./build --config MinSizeRel --target all --

      - name: just to see if built dll can be imported
        run: |
          cp tests/test_justforci.py build/fftwtest
          cd build && python -c "import tmphmwk"
          cd fftwtest && python test_justforci.py
          rm test_justforci.py && cd ../../
