name: gcc try fftw

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 2a6371b01420d8820d158b4707e79931feba27aa
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'

      - name: Install fftw
        run: ${{ github.workspace }}/vcpkg/vcpkg install fftw3[avx2,sse2,core,openmp]
      - name: Install ninja
        run: sudo apt install neofetch ninja-build && pip install numpy scipy && neofetch
      - name: configure
        run: cmake -S . -B ./build -G Ninja -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: build
        run: cmake --build ./build --config MinSizeRel --target all --

      - name: just to see if built dll can be imported
        run: |
          cp tests/test_justforci.py build/fftwtest
          cd build && python -c "import tmphmwk"
          cd fftwtest && python test_justforci.py
